// Mock data for the application
export const mockUsers = [
  {
    id: '1',
    email: 'john@example.com',
    username: 'john_doe',
    profilePicture: 'https://i.pravatar.cc/150?img=1',
  },
  {
    id: '2',
    email: 'jane@example.com',
    username: 'jane_smith',
    profilePicture: 'https://i.pravatar.cc/150?img=2',
  },
  {
    id: '3',
    email: 'bob@example.com',
    username: 'bob_johnson',
    profilePicture: 'https://i.pravatar.cc/150?img=3',
  },
  {
    id: '4',
    email: 'alice@example.com',
    username: 'alice_williams',
    profilePicture: 'https://i.pravatar.cc/150?img=4',
  },
];

export const mockProjects = [
  {
    id: 'proj-1',
    projectName: 'Website Redesign',
    description: 'Redesign the company website with modern UI/UX',
    ownerId: '1',
    members: ['1', '2', '3'],
    createdDate: '2024-11-01',
    updatedDate: '2024-11-15',
  },
  {
    id: 'proj-2',
    projectName: 'Mobile App Development',
    description: 'Build a cross-platform mobile application',
    ownerId: '2',
    members: ['2', '3', '4'],
    createdDate: '2024-11-05',
    updatedDate: '2024-11-18',
  },
  {
    id: 'proj-3',
    projectName: 'API Integration',
    description: 'Integrate third-party payment and analytics APIs',
    ownerId: '1',
    members: ['1', '4'],
    createdDate: '2024-11-10',
    updatedDate: '2024-11-19',
  },
];

export const mockTasks = [
  // Website Redesign Project Tasks
  {
    id: 'task-1',
    projectId: 'proj-1',
    title: 'Create wireframes',
    description: 'Design wireframes for all main pages',
    status: 'DONE',
    priority: 'HIGH',
    assignedTo: '2',
    dueDate: '2024-11-12',
    createdBy: '1',
    createdDate: '2024-11-01',
    updatedDate: '2024-11-10',
    comments: [
      {
        id: 'comment-1',
        userId: '2',
        text: 'Wireframes completed and reviewed',
        timestamp: '2024-11-10T10:30:00Z',
      },
    ],
  },
  {
    id: 'task-2',
    projectId: 'proj-1',
    title: 'Design mockups',
    description: 'Create high-fidelity mockups in Figma',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    assignedTo: '2',
    dueDate: '2024-11-20',
    createdBy: '1',
    createdDate: '2024-11-05',
    updatedDate: '2024-11-18',
    comments: [],
  },
  {
    id: 'task-3',
    projectId: 'proj-1',
    title: 'Frontend development',
    description: 'Implement React components based on mockups',
    status: 'TODO',
    priority: 'HIGH',
    assignedTo: '3',
    dueDate: '2024-12-01',
    createdBy: '1',
    createdDate: '2024-11-08',
    updatedDate: '2024-11-08',
    comments: [],
  },
  {
    id: 'task-4',
    projectId: 'proj-1',
    title: 'Setup database schema',
    description: 'Design and setup MongoDB collections',
    status: 'TODO',
    priority: 'MEDIUM',
    assignedTo: '1',
    dueDate: '2024-11-25',
    createdBy: '1',
    createdDate: '2024-11-09',
    updatedDate: '2024-11-09',
    comments: [],
  },

  // Mobile App Development Project Tasks
  {
    id: 'task-5',
    projectId: 'proj-2',
    title: 'Setup React Native project',
    description: 'Initialize React Native project with TypeScript',
    status: 'DONE',
    priority: 'HIGH',
    assignedTo: '3',
    dueDate: '2024-11-08',
    createdBy: '2',
    createdDate: '2024-11-05',
    updatedDate: '2024-11-07',
    comments: [],
  },
  {
    id: 'task-6',
    projectId: 'proj-2',
    title: 'User authentication screens',
    description: 'Build login and signup screens',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    assignedTo: '4',
    dueDate: '2024-11-22',
    createdBy: '2',
    createdDate: '2024-11-08',
    updatedDate: '2024-11-17',
    comments: [
      {
        id: 'comment-2',
        userId: '4',
        text: 'Login screen done, working on signup validation',
        timestamp: '2024-11-17T14:15:00Z',
      },
    ],
  },
  {
    id: 'task-7',
    projectId: 'proj-2',
    title: 'Main dashboard UI',
    description: 'Create main dashboard with navigation',
    status: 'TODO',
    priority: 'MEDIUM',
    assignedTo: '3',
    dueDate: '2024-11-28',
    createdBy: '2',
    createdDate: '2024-11-10',
    updatedDate: '2024-11-10',
    comments: [],
  },

  // API Integration Project Tasks
  {
    id: 'task-8',
    projectId: 'proj-3',
    title: 'Stripe payment integration',
    description: 'Integrate Stripe for payment processing',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    assignedTo: '1',
    dueDate: '2024-11-25',
    createdBy: '1',
    createdDate: '2024-11-10',
    updatedDate: '2024-11-18',
    comments: [],
  },
  {
    id: 'task-9',
    projectId: 'proj-3',
    title: 'Google Analytics setup',
    description: 'Configure Google Analytics for tracking',
    status: 'TODO',
    priority: 'MEDIUM',
    assignedTo: '4',
    dueDate: '2024-11-30',
    createdBy: '1',
    createdDate: '2024-11-12',
    updatedDate: '2024-11-12',
    comments: [],
  },
];
